### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by LukasSandm** [autotraderuk/oliver-twist#35]
Hey team,
thanks for the great work with olivertwist!

We are using olivertwist in the CircleCI pipeline in one of our dbt projects and it works great. When rolling it out to other dbt projects I encountered an issue. Set up for olivertwist is the same and I am not aware of any difference in the dbt project that could explain this.

I am not sure how to debug this, so wanted to check if you have any ideas or pointers for me. I also had talked to a colleague that had the same issue in a different dbt project, so it seems not just my local set up.

Let me know if there is a better place or way to report issues like this. And also if you would need more information around set up to troubleshoot this.

Thank you!

Version: olivertwist  0.2

Traceback:
```
Traceback (most recent call last):
  File "/.venv/bin/olivertwist", line 8, in <module>
    sys.exit(main())
  File "/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/.venv/lib/python3.8/site-packages/olivertwist/main.py", line 66, in check
    results = rule_engine.run(manifest)
  File "/.venv/lib/python3.8/site-packages/olivertwist/ruleengine/engine.py", line 44, in run
    return [Result(rule, *rule.apply(manifest)) for rule in self.rules]
  File "/.venv/lib/python3.8/site-packages/olivertwist/ruleengine/engine.py", line 44, in <listcomp>
    return [Result(rule, *rule.apply(manifest)) for rule in self.rules]
  File "/.venv/lib/python3.8/site-packages/olivertwist/ruleengine/rule.py", line 30, in apply
    return self.func(manifest)
  File "/.venv/lib/python3.8/site-packages/olivertwist/rules/no_references_outside_of_its_staging_area.py", line 35, in no_references_outside_of_its_own_staging_area
    return list(passes), list(failures)
  File "/.venv/lib/python3.8/site-packages/olivertwist/rules/no_references_outside_of_its_staging_area.py", line 24, in staging_depends_on_staging_in_another_area
    different_staging_area_refs = [
  File "/.venv/lib/python3.8/site-packages/olivertwist/rules/no_references_outside_of_its_staging_area.py", line 28, in <listcomp>
    if not manifest.get_node(p).area == node.area
  File "/.venv/lib/python3.8/site-packages/olivertwist/manifest.py", line 95, in area
    return self.data["fqn"][2]
IndexError: list index out of range
```

**Comment by dorzey** [comment]
@LukasSandm was any progress made on this issue?

**Comment by LukasSandm** [comment]
@dorzey thank you for your reply. Unfortunately not. Any pointers or ideas how to resolve this?

**Comment by dorzey** [comment]
@LukasSandm I think it's possible that we've made a faulty assumption about how many times appear in the `fqn` array. Is it possible for you to share the `manifest.json` that is causing this problem?
